default_config:
  default_host_group: global_group
  log_file: zabbix_util.log
  regex_format: "^.*{}.*"
  log_item_key: "log[{},@{},,,skip,]"

zabbix_masters:
  - zone_name: PSKRW1
    host: 27.72.232.43
    port: 3532
    ssl: false
    user: dh.hung
    password: Zabbix.123#
  - zone_name: MES01
    host: 172.168.116.227
    port: 80
    ssl: false
    user:
    password: